"""Randen Studio 路由表——仅定义 API 端点映射，业务逻辑在 handlers.py。"""

from __future__ import annotations

from typing import Any

from .handlers import (
    handle_chat,
    handle_context,
    handle_continuity,
    handle_document_create,
    handle_document_read,
    handle_document_write,
    handle_export,
    handle_focus,
    handle_foreshadowing,
    handle_health,
    handle_import,
    handle_model,
    handle_project_init,
    handle_review,
    handle_source,
    handle_sync,
    handle_workspace,
    handle_write,
    handle_market,
    handle_dissect,
    handle_dissect_deep,
    handle_dissect_multi,
    handle_merge_dissections,
    handle_idea,
    handle_opening,
    handle_faq,
    handle_save_result,
    handle_character_guide,
    handle_generate_outline,
    handle_epub_extract,
    handle_ai_dissect,
    handle_ai_imitate,
    handle_dna_extract,
    handle_dna_blend,
    handle_persona_template,
    handle_persona_save,
    handle_persona_load,
    handle_material_list,
    handle_material_create,
    handle_material_update,
    handle_material_delete,
    handle_ai_story,
    handle_ai_character,
    handle_ai_world,
    handle_model_list,
    handle_inspire_apply,
    handle_inspire_vision,
)

# (处理器, 是否需要项目已初始化)
GET_ROUTES: dict[str, tuple[Any, bool]] = {
    "/api/health":     (handle_health,     False),
    "/api/workspace":  (handle_workspace,  False),
    "/api/continuity": (handle_continuity, True),
    "/api/context":    (handle_context,    True),
    "/api/document":   (handle_document_read, True),
}

POST_ROUTES: dict[str, tuple[Any, bool]] = {
    "/api/project/init":      (handle_project_init,    False),
    "/api/focus":             (handle_focus,           False),
    "/api/model":             (handle_model,           False),
    "/api/market":            (handle_market,          False),
    "/api/dissect":           (handle_dissect,         False),
    "/api/dissect/deep":      (handle_dissect_deep,    False),
    "/api/dissect/multi":     (handle_dissect_multi,   False),
    "/api/dissect/merge":     (handle_merge_dissections, False),
    "/api/idea":              (handle_idea,            False),
    "/api/opening":           (handle_opening,         False),
    "/api/faq":               (handle_faq,             False),
    "/api/save":              (handle_save_result,     False),
    "/api/character_guide":   (handle_character_guide, False),
    "/api/generate_outline":  (handle_generate_outline, False),
    "/api/epub":              (handle_epub_extract,    False),
    "/api/ai_dissect":        (handle_ai_dissect,      False),
    "/api/ai_imitate":        (handle_ai_imitate,      False),
    "/api/dna/extract":       (handle_dna_extract,       False),
    "/api/dna/blend":         (handle_dna_blend,         False),
    "/api/persona/template":  (handle_persona_template, False),
    "/api/persona/save":      (handle_persona_save,    False),
    "/api/persona/load":      (handle_persona_load,    False),
    "/api/materials":          (handle_material_list,   True),
    "/api/material/create":    (handle_material_create, True),
    "/api/material/update":    (handle_material_update, True),
    "/api/model/list":        (handle_model_list,      False),
    "/api/ai/story":           (handle_ai_story,          True),
    "/api/ai/character":       (handle_ai_character,      True),
    "/api/ai/world":           (handle_ai_world,          True),
    "/api/inspire/apply":     (handle_inspire_apply,    True),
    "/api/inspire/vision":    (handle_inspire_vision,   False),
    "/api/sanitize":          (handle_sanitize,         False),
    "/api/negotiate":         (handle_negotiate,        False),
    "/api/redraw":            (handle_redraw,           False),
    "/api/cross-domain":      (handle_cross_domain,     False),
    "/api/adapt-drama":       (handle_adapt_drama,      False),
    "/api/material/delete":    (handle_material_delete, True),
    "/api/write":             (handle_write,           True),
    "/api/review":            (handle_review,          True),
    "/api/sync":              (handle_sync,            True),
    "/api/document/create":   (handle_document_create, True),
    "/api/import":            (handle_import,          True),
    "/api/foreshadowing":     (handle_foreshadowing,   True),
    "/api/chat":              (handle_chat,            True),
    "/api/source":            (handle_source,          True),
}
